services:
  web:
    container_name: flash-cards-web
    build:
      context: .
    image: flash-cards-web
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db

  db:
    container_name: flash-cards-db
    image: mysql:9.2
    restart: always
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=${DB_PASS}
     - MYSQL_DATABASE=${DB_NAME}
    volumes:
     - ~/Projects/flash-cards/db:/var/lib/mysql